[package]
name = "chomper2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing            = "*"
tracing-subscriber = "*"
log                = "*"
ctor               = "*"
tracing-log        = "*"
lazy_static        = "*"

[dependencies.text-edit]
version = "*"
path = "../rust-analyzer/crates/text-edit"

[dependencies.chomper-plugin]
version = "*"
path = "../chomper-plugin"

[dependencies.syntax]
version = "*"
path = "../rust-analyzer/crates/syntax"

[dependencies.ide]
version = "*"
path = "../rust-analyzer/crates/ide"
